hypercall: fix definition of enum mv_cpuid_flag_t
The enum mv_cpuid_flag_t is incorrectly defined as mv_cpuid_flag
(missing the _t suffix) in the C header file, which causes the following
build errors:

/home/nr/bareflank/microv/hypercall/include/mv_cdl_entry_t.h:51:9: error: User-defined types must have the same name as the header file they are defined in. Either name the Enum 'mv_cdl_entry_t', or name the header 'mv_cpuid_flag_t' [bsl-user-defined-type-names-match-header-name,-warnings-as-errors]
        enum mv_cpuid_flag_t flags;
        ^
/home/nr/bareflank/microv/hypercall/include/mv_cdl_entry_t.h:51:14: error: Enum 'mv_cpuid_flag_t' is missing documentation. Are you missing the '@brief' command? [bsl-documentation,-warnings-as-errors]
        enum mv_cpuid_flag_t flags;
             ^
/home/nr/bareflank/microv/hypercall/include/mv_cdl_entry_t.h:51:30: error: field has incomplete type 'enum mv_cpuid_flag_t' [clang-diagnostic-error]
        enum mv_cpuid_flag_t flags;
                             ^
/home/nr/bareflank/microv/hypercall/include/mv_cdl_entry_t.h:51:14: note: forward declaration of 'enum mv_cpuid_flag_t'
        enum mv_cpuid_flag_t flags;
             ^
/home/nr/bareflank/microv/hypercall/include/mv_cpuid_flag_t.h:46:1: error: User-defined types must have the same name as the header file they are defined in. Either name the Enum 'mv_cpuid_flag_t', or name the header 'mv_cpuid_flag' [bsl-user-defined-type-names-match-header-name,-warnings-as-errors]
enum mv_cpuid_flag
^

Fix this by adding the _t suffix in the C header file.

Signed-off-by: Nick Rosbrook <rosbrookn@ainfosec.com>